services:
  store-db:
    image: mysql:8.0
    container_name: store-db
    env_file:
      - ./.env.docker
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - coffeedoor-network

networks:
  coffeedoor-network:
      external: true

volumes:
  mysql-data:
